---

sudo: required
language: ruby
rvm:
  - 2.3

services:
  - docker

install:
  - mkdir -p "$HOME/bin"
  - curl -Lso "$HOME/bin/shellcheck" https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.6/shellcheck
  - chmod +x "$HOME/bin/shellcheck"
  - rvm install "$(cat .ruby-version)"
  - sudo pip install pre-commit
  - make bundle-install

script:
  - make test
